name: custom_border
description: "A flutter package to add border(dotted,dashed,lined,...) for all widgets"
version: 1.0.3
repository: https://github.com/abbasghasemi/flutter-border
homepage: https://github.com/abbasghasemi/flutter-border
issue_tracker: https://github.com/abbasghasemi/flutter-border/issues

topics:
  - dotted
  - dashed
  - lined
  - gradient
  - animated

environment:
  sdk: ^2.17.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter